services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=metervision
    volumes:
      - metervision_postgres_data:/bitnami/postgresql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/metervision?schema=public
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
     - postgres
    command: sh -c "pnpm prisma migrate deploy && pnpm start"

volumes:
  metervision_postgres_data:
